### ISSUE TITLE
MATSim error when running Kelheim test Scenario

### ISSUE THREAD

**Issue by syhwawa** [matsim-scenarios/matsim-kelheim#68]
Hi, I am encountering an error with a missing file file `kelheim-v3.1-routes-ref.csv.gz` when attempting to run the MATSim Kelheim test scenario at `matsim-kelheim/input/test.config.xml`.

I used the following command to run the test config

```bash
java -cp matsim-kelheim-3.x-SNAPSHOT-3b6618e.jar \
org.matsim.run.RunKelheimScenario run \
--post-processing disabled \
--config /Users/yuhao.sun/Personal_projects/matsim-org/matsim-kelheim/input/test.config.xml
```

The simulation fails to start, throwing the following error:
```
ERROR MatsimRuntimeModifications:105 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
java.io.UncheckedIOException: java.io.FileNotFoundException: kelheim-v3.1-routes-ref.csv.gz
	at org.matsim.core.utils.io.IOUtils.resolveFileOrResource(IOUtils.java:258)
	at org.matsim.dashboards.KelheimDashboardProvider.getDashboards(KelheimDashboardProvider.java:28)
	at org.matsim.simwrapper.SimWrapperListener.addFromProvider(SimWrapperListener.java:94)
	at org.matsim.simwrapper.SimWrapperListener.generate(SimWrapperListener.java:75)
	at org.matsim.simwrapper.SimWrapperListener.notifyStartup(SimWrapperListener.java:49)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerStartupEvent(ControlerListenerManagerImpl.java:113)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:70)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:53)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:83)
	at org.matsim.core.controler.Controler.run(Controler.java:259)
	at org.matsim.application.MATSimApplication.call(MATSimApplication.java:199)
	at org.matsim.application.commands.RunScenario.call(RunScenario.java:16)
	at org.matsim.application.commands.RunScenario.call(RunScenario.java:8)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.matsim.application.MATSimApplication.run(MATSimApplication.java:450)
	at org.matsim.run.RunKelheimScenario.main(RunKelheimScenario.java:125)
Caused by: java.io.FileNotFoundException: kelheim-v3.1-routes-ref.csv.gz
	at org.matsim.core.utils.io.IOUtils.resolveFileOrResource(IOUtils.java:256)
	... 24 more
```

Could you please provide guidance on how to resolve this issue? Is there a specific location from where I should obtain kelheim-v3.1-routes-ref.csv.gz, or is there a step I might be missing in the setup process? Any help or pointers would be greatly appreciated.

**Comment by syhwawa** [comment]
Hi, I have switched to using release version 3.0, but I am still encountering the same error when attempting to run the simulation using the test configuration.

**Comment by tschlenther** [comment]
strange i just ran the test config successfully from the `3.0` branch with `RunKelheimScenario`..
BTW that config is normally just included for the unit tests. Can you try running the normal config (for that you don't have to provide a `--config` flag at all). The Kelheim scenario is pretty small, if you run `--1pct` it should be quick and small...

**Comment by syhwawa** [comment]
> strange i just ran the test config successfully from the `3.0` branch with `RunKelheimScenario`.. BTW that config is normally just included for the unit tests. Can you try running the normal config (for that you don't have to provide a `--config` flag at all). The Kelheim scenario is pretty small, if you run `--1pct` it should be quick and small...

Hi @tschlenther , thank you for your prompt response. I tried using `--1pct `instead of specifying a particular config. The simulation is now running smoothly! 

In terms of method providing `--config`, I downloaded the input files(plans, vehicles and network inputs) linked in `matsim-kelheim/input/test.config.xml` and edited the paths to point to the downloaded files before running the simulation. I'm curious about why I encountered that error initially.

By the way, do you know which configuration is used when we run `--1pct`? We may consider make some adjustments to create tailored scenarios. Thanks very much.

**Comment by rakow** [comment]
It should be fixed on the master branch now. @tschlenther dashboards are disabled in the test, so it is not covered. Last time, the test runner on github didn't have enough resources to run the sim + post-processing.
